### PR TITLE
fix: sticky item width calculation

### PR DESCRIPTION
**Pull request by gorhom**
closing #12

### CODE REVIEW

**Comment by Hirbod** [comment]
Well this release broke the sticky item for me :/

**Comment by Hirbod** [comment]
IMG_0349

**Comment by Hirbod** [comment]
Even your default FacebookStickyStoryStyled is broken :/
https://streamable.com/of3zvg

**Comment by gorhom** [comment]
hi @Hirbod , sorry to hear that, this actually meant to be a fix, but i think the calculation broke current implementation

i had to redo the Facebook Styled example 
Simulator Screen Shot - iPhone 11 - 2020-06-01 at 23 28 12

however, i'll try to revert this merge and release it as major

**Comment by Hirbod** [comment]
Look like the issue happens because I've set my stickyItemWidth and height to 32. It works when I set it to 46x46 @gorhom

**Comment by Hirbod** [comment]
Yes, setting to anything lower then 46x46 breaks it, but 46x46 works fine

**Comment by gorhom** [comment]
i have reverted this merge , i'll test it more with small number

**Comment by gorhom** [comment]
you should be able to get `v1.3.1` without this pr

**Comment by Hirbod** [comment]
This is how v.1.3.1 looks now
IMG_0351

The resizing works fine now, but the offset is broken
Here also a video
https://streamable.com/ck5v46

**Comment by Hirbod** [comment]
Ok I could fix this by changing
```  
const animatedThumbnailTranslateX = interpolate(x, {
    inputRange: [separatorSize, threshold],
    outputRange: [0, isRTL ? separatorSize : -separatorSize],
    extrapolate: Extrapolate.CLAMP,
  });
```

**Pull request merged**
