### PR TITLE
feat: handle initial index

### PR DESCRIPTION
**Pull request by gorhom**
closing #4 , #5

### CODE REVIEW

**Comment by gorhom** [comment]
hi @Hirbod , could you test this pr , it should close #4 and #5 

```bash
yarn add ssh://git@github.com:gorhom/react-native-sticky-item#feature/handle-initial-index
```

**Comment by Hirbod** [comment]
Hi @gorhom,

thanks, I will check that out. I see you have imported TouchableOpacity from RNGH, let me see if this works for me without that (cause I am using TouchableScale).
And I've seen that you implemented getItemLayout (I also did this locally, but even better if the library takes care of that)

I'll report back, gonna test this now

**Comment by Hirbod** [comment]
Hi @gorhom, I tried your fixes and they work indeed, but as I thought, only when I import TouchableOpacity from RNGH. Not exactly what I would love to use, since I am using https://github.com/kohver/react-native-touchable-scale, but its ok for me. Using TouchableOpacity on my Item with your fixes works great on that Hitslop.

**Comment by gorhom** [comment]
glad to hear that, and indeed TouchableOpacity from RNGH will always be better suitable with gesture handler interactions.

Thanks for reporting/testing it :)

**Comment by Hirbod** [comment]
You're welcome, thanks for your work. I will fork touchable-scale and rework it to use RNGH, it should work afterwards like I need it.

**Pull request merged**
