### PR TITLE
refactor: copy redash used functionality

### PR DESCRIPTION
**Pull request by gorhom**
#22 

## Motivation

in this pr, i have embedded the used functionalities from Redash, to allow user to install latest version without having conflict.

## Testing

```
yarn add ssh://git@github.com:gorhom/react-native-sticky-item#feature/clone-redash-functionality
```

### CODE REVIEW

**Comment by gorhom** [comment]
@Hirbod could you test this pr and let me know if it fixes your issue, thanks

**Comment by Hirbod** [comment]
@gorhom yupp, crash is gone. I tried a similar path but failed to parse the SVG. 
The only thing thats left (but not important for #22) is

```
%s: Calling getNode() on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release., FlatList, getNode()
```

StickyItemFlatlist.tsx, 157

```
    useImperativeHandle(ref, () => flatListRef.current!.getNode());
```

**Comment by Hirbod** [comment]
@gorhom do you need any further assistance for a new release? This PR fixes the crash issue. Not sure what you think about the getNode warning.

**Comment by gorhom** [comment]
@Hirbod thanks for testing this PR, i look into `getNode` warning this weekend, sorry for the delay

**Pull request merged**
